#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DOTDIR="$HOME/.dotfiles"

export EDITOR="nvim"
export VISUAL="nvim"

# Expose git custom commands
export PATH="$HOME/.gitcmd:$PATH"

# fzf
export FZF_DEFAULT_COMMAND='rg --hidden --ignore .git/ -l -g ""'
export FZF_CTRL_T_COMMAND='rg --hidden --ignore .git/ -l -g ""'
export FZF_COMPLETION_TRIGGER=''
export FZF_DEFAULT_OPTS="--bind 'down:preview-page-down,up:preview-page-up'"

# Local env
[ -f $HOME/.zshenv.local ] && source $HOME/.zshenv.local
