#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DOTDIR="$HOME/.dotfiles"

export EDITOR="vim"
export VISUAL="vim"

# Expose git custom commands
export PATH="$HOME/.gitcmd:$PATH"

# Add rbenv to user's path
if [ -d $HOME/.rbenv ]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
fi

[ -f $HOME/.zshenv.local ] && source $HOME/.zshenv.local
