#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Map kj to ESC in shell 
bindkey kj vi-cmd-mode

# Adjust fpath to load custom functions
fpath=($HOME/.zfunc $fpath)
autoload -Uz $HOME/.zfunc/*(:t)

# Source nvm
[[ -s $HOME/.nvm/nvm.sh ]] && source $HOME/.nvm/nvm.sh && nvm use stable > /dev/null 1>&1

# Add rbenv to user's path
if [[ -d $HOME/.rbenv ]]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

# Load aliases
[[ -f $HOME/.shell_aliases ]] && source $HOME/.shell_aliases

